### ISSUE TITLE
I don't give permission to use Disqordia in your site

### ISSUE THREAD

**Issue by erisdisqordia** [federater/federater.github.io#1]
I ask that you take down the Disqordia page and delete any information regarding it as you do not have permission to use my content. You did not request my permission and you are not given it. 

I run the site, and you are requested to remove it. This thread will be used in Github reports if that doesn't happen as failure to do so goes against Github's rules. 

Thank you.

Links to content:
https://federater.github.io/disqordia-space.html
https://github.com/federater/federater.github.io/blob/main/_posts/2023-01-06-disqordia-space.md

**Comment by Mg138** [comment]
Why is this closed as invalid? The entry was not removed.

**Comment by Mg138** [comment]
The Internet is not a place where you can just link to other things and share information about things freely, if a site owner requests that you take down something regarding their site you ought to do it.

If you believe that you're not at fault, you're the same as the freespeech extremist people.

**Comment by mc776** [comment]
> The Internet is not a place where you can just link to other things and share information about things freely, if a site owner requests that you take down something regarding their site you ought to do it.
> 
> If you believe that you're not at fault, you're the same as the freespeech extremist people.

It's not wrong if the right people do it!

Real Harry Potter morality hours with whoever's making this disgusting thing.
